# Generated by Django 4.0.4 on 2022-06-09 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trackerr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("E", "Email"),
                            ("A", "Company Address"),
                            ("C", "Contact Number"),
                        ],
                        max_length=1,
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trackerr.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Detail",
                "verbose_name_plural": "Company Details",
            },
        ),
    ]
