# Generated by Django 4.0.4 on 2022-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerr', '0002_companydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
