# Generated by Django 4.0.4 on 2022-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerr', '0003_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank='', default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(blank='', default='', max_length=11),
        ),
    ]
