# Generated by Django 4.0.4 on 2022-06-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerr', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applying_date',
        ),
    ]
